apiVersion: apps/v1
kind: Deployment
metadata:
  name: newpetshop
spec:
  selector:
    matchLabels:
      app: newpetshop
  replicas: 1 
  template: 
    metadata:
      labels:
        app: newpetshop
    spec:
      containers:
      - name: pradeepcontainer
        image: pradeepdocker273/newpetstore:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petshop
spec:
  type: LoadBalancer
  selector:
    app: newpetshop
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
